server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
logging:
  level:
    org: error
    com: off
---
spring:
  profiles:
    active: prod
---
spring:
  sql:
    init:
      mode: always
  #      schema-locations: classpath:hr_schema_postgres.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  config:
    activate:
      on-profile: prod
---

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      generate_ststistics: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  config:
    activate:
      on-profile: local

